{
  try {
    execPool.checkout(dest);
    fail("should have thrown an connection exception");
  }
 catch (  UnreachableStoreException e) {
    assertEquals("inner exception should be of type connect exception",expectedExceptionClass,e.getCause().getClass());
  }
}
